FROM jncc/snap-base:0.0.0.2

# Setup app folder
WORKDIR /app

# Configure apt
RUN apt-get update && apt-get -y install \ 
    apt-utils \
    build-essential \
    software-properties-common \
    git \
    bc 

# Install packages from apt
RUN add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update && apt-get -y install \
    python3.7 \
    python-setuptools \
    python-gdal \
    gdal-bin

# Setup python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1 \
    && easy_install pip \
    && pip install \
        virtualenv

# --------- Place machine build layers before this line ---------

# Install snap toolbox scripts.
COPY /app/toolchain/scripts /app/toolchain/scripts

# Copy toolchain config
COPY config/app/toolchain/scripts/JNCC_S1_GRD_configfile_v.1.1.sh /app/toolchain/scripts

# Copy workflow requirements
COPY app/workflows/requirements.txt /app/workflows/

# Remove static gpt memory configuration
RUN rm /app/snap/bin/gpt.vmoptions

# Copy build config
COPY config/app/workflows/build-config.json ./

# Build virtual env
COPY config/app/workflows/install-venv.sh /app/workflows
RUN chmod +x ./workflows/install-venv.sh \
    && ./workflows/install-venv.sh \
    && rm -f ./workflows/install-venv.sh

# Create processing paths
RUN mkdir /input/ \
    && mkdir /static/ \
    && mkdir /state/ \
    && mkdir /working/ \
    && mkdir /output/ 

# Copy the singularity test script
COPY app/test-luigi.sh ./

# Initialise startup script
COPY app/exec.sh ./
RUN chmod +rx /app/exec.sh
COPY app/CopyState.py ./

# Copy the workflow
COPY app/workflows ./workflows

# Copy workflow config
COPY config/app/workflows/luigi.cfg /app/workflows
RUN chmod +r ./workflows/luigi.cfg

# Copy container readme
COPY app/readme.md ./

ENTRYPOINT ["/app/exec.sh"]
