ARG BASE_IMAGE=jncc/s1-ard-processor-dev:1.0.24-SNAP-12.0.0
FROM ${BASE_IMAGE}

# Setup app folder
WORKDIR /app

# Configure apt
RUN apt-get update && apt-get -y install \ 
    apt-utils \
    build-essential \
    software-properties-common \
    git \
    bc \
    python3-venv

# --------- Place machine build layers before this line ---------

# Install snap toolbox scripts.
COPY /app/toolchain/scripts /app/toolchain/scripts

# Copy toolchain config
COPY config/app/toolchain/scripts/JNCC_S1_GRD_configfile_v.1.1.sh /app/toolchain/scripts

# Copy workflow requirements
COPY app/workflows/requirements.txt /app/workflows/

# Copy build config
COPY config/app/workflows/build-config.json ./

# Build virtual env
COPY config/app/workflows/install-venv.sh /app/workflows
RUN chmod +x ./workflows/install-venv.sh \
    && ./workflows/install-venv.sh \
    && rm -f ./workflows/install-venv.sh

# Create processing paths
RUN mkdir /input/ \
    && mkdir /static/ \
    && mkdir /state/ \
    && mkdir /working/ \
    && mkdir /output/ \
    && mkdir /report/ \
    && mkdir /database/

# Copy the apptainer test script
COPY app/test-luigi.sh ./

# Initialise startup script
COPY app/exec.sh ./
RUN chmod +rx /app/exec.sh
COPY app/CopyState.py ./

# Copy the workflow
COPY app/workflows ./workflows

# Copy workflow config
COPY config/app/workflows/luigi.cfg /app/workflows
RUN chmod +r ./workflows/luigi.cfg

# Copy container readme
COPY app/readme.md ./

ENTRYPOINT ["/app/exec.sh"]
