#!/bin/bash

# Set and read PIDfile
PIDFILE=/var/run/make_s1_ard.pid
if [ -f $PIDFILE ]
then
    PID=$(cat $PIDFILE)
    ps -p $PID > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
        # Job is already running
        exit 1
    else
        # No process with PID assume we are not running already
        echo $$ > $PIDFILE
        if [ $? -ne 0 ]
        then
            echo "Could not create PIDFile"
            exit 1
        fi
    fi
else
    echo $$ > $PIDFILE
    if [ $? -ne 0 ]
    then
        echo "Could not create PIDFile"
        exit 1
    fi
fi

# Activate appropriate virtualenv to push correct path variables in
source /luigi/workflow-venv/bin/activate
# Run ProcessRawS1Files luigi step to run through all data
(cd /luigi/workflows && PYTHONPATH='.' luigi --module make_s1_ard ProcessRawS1Files)
# Deactivate virtualenv 
deactivate
# Remove PIDFile
rm $PIDFILE