FROM ubuntu:22.04

# Setup app folder
WORKDIR /app

RUN apt-get update && apt-get -y install \ 
    python3-software-properties \
    python3-setuptools \
    wget \
    expect \
    libgfortran5 \
    fonts-dejavu

# Install snap toolbox with default settings
RUN wget https://download.esa.int/step/snap/10_0/installers/esa-snap_sentinel_linux-10.0.0.sh
RUN sh esa-snap_sentinel_linux-10.0.0.sh -q \
    && rm -f esa-snap_sentinel_linux-10.0.0.sh

# Configure snap toolbox
COPY config/app/snap/bin/gpt.vmoptions ./snap/bin