FROM ubuntu:20.04

# Setup app folder
WORKDIR /app

RUN apt-get update && apt-get -y install \ 
    python3-software-properties \
    python3-setuptools \
    wget \
    expect \
    libgfortran5 \
    ttf-dejavu

# Install snap toolbox
COPY config/app/install-snap.sh /app
RUN wget http://step.esa.int/downloads/8.0/installers/esa-snap_all_unix_8_0.sh \
    && chmod +x install-snap.sh 

RUN expect -f ./install-snap.sh \
    && rm install-snap.sh \
    && rm esa-snap_all_unix_8_0.sh 

# Copy update script, current snap hangs at end of toolbox update so need to scan for
# finished update line and then kill the process
COPY config/app/update-snap.sh /app
RUN chmod +x update-snap.sh \ 
    && ./update-snap.sh \
    && rm update-snap.sh

# Configure snap toolbox
COPY config/app/snap/bin/gpt.vmoptions ./snap/bin